[build]
  # Build command
  command = "npm run build:prod"
  
  # Directory to publish (Angular builds to dist/customer-manager by default)
  publish = "dist/customer-manager"

# Redirect rules for Angular SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Environment variables for production
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Optional: Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
